# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: efriedma <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/01/30 22:48:49 by efriedma          #+#    #+#              #
#    Updated: 2019/01/31 12:17:03 by efriedma         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC = clang++
FLAGS = -Wall -Wextra -Werror  
SRC=whatever.cpp 
EXE=template

all:
	$(CC) $(FLAGS) $(SRC) -o $(EXE)

clean:
	rm -f $(EXE)

re: clean all

