# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: efriedma <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/01/23 11:20:18 by efriedma          #+#    #+#              #
#    Updated: 2019/01/23 14:01:52 by efriedma         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	clang++ -Wall -Wextra -Werror Zombie.cpp main.cpp ZombieFactory.cpp -o zombie

clean:
	rm -f zombie

re: clean all
