# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: efriedma <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/01/22 15:52:32 by efriedma          #+#    #+#              #
#    Updated: 2019/01/22 15:53:54 by efriedma         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	clang++ -Wall -Wextra -Werror Contact.class.cpp main.cpp

clean:
	rm -f a.out

re: clean all 

